M48
; DRILL file {KiCad 6.0.9-8da3e8f707~116~ubuntu20.04.1} date Thu Mar 23 19:36:49 2023
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-03-23T19:36:49+00:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,6.0.9-8da3e8f707~116~ubuntu20.04.1
; #@! TF.FileFunction,MixedPlating,1,2
FMAT,2
METRIC
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T1C1.520
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
%
G90
G05
T1
X12.5Y-26.0
X17.58Y-26.0
T2
X4.0Y-4.0
X15.0Y-15.0
X26.0Y-4.0
T0
M30
